name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14


      - name: Build & Release app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: "--x64 --ia32 --win portable"
          github_token: ${{ secrets.github_token }}
          release: true
